#!/usr/bin/env bash
# Script that configures HAproxy in a load balancerr 
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 3262-web-01 44.210.239.243:80 check\n\tserver 3262-web-02 44.192.84.15:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
