#!/usr/bin/env bash
#Sets nginx for listening to 80 port
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
sudo service nginx reload
