#!/usr/bin/env bash
# Script that sets the port 80
sed -i "s/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:80 default_server ipv4only=on;/" /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default
service nginx reload
